version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    deleteFiles: true
hooks:
  AfterInstall:
    - location: /
      timeout: 300
      runas: root
      command: |
        cd /usr/local/bin
        ./test.sh
